import React from 'react'
import b1 from '../assects/b1.png'
import b2 from '../assects/b2.png'
import b3 from '../assects/b3.png'
import b4 from '../assects/b4.png'
import b5 from '../assects/b5.png'
import b6 from '../assects/b6.png'
import b7 from '../assects/b7.png'

const Popular = () => {
    return (
        <div>
            <div className='flex flex-col items-center w-full 2xl:px-[144px] xl:px-[100px] px-[30px] py-[100px] text-white bg-black gap-[30px]'>
                <div className='font-zen-dots text-3xl md:text-4xl lg:text-5xl xl:text-6xl 2xl:text-7xl font-normal leading-tight text-center'>
                    Popular NFT’s generated by Artists
                </div>
                <div className='text-center text-lg md:text-xl lg:text-2xl xl:text-3xl 2xl:text-4xl font-normal leading-relaxed'>
                    3dotlink's AI integration is a game-changer in the NFT art world. It offers a powerful canvas for artists to redefine art creation and innovation while preserving cultural art in an entirely new format. With this platform, the convergence of human ingenuity and AI technology is set to redefine the boundaries of artistic expression and creative possibilities, ushering in a digital art renaissance.
                </div>
                <div class="md:grid md:grid-cols-4 gap-4 text-white w-full md:h-[1200px] mt-[40px] flex flex-col flex-wrap">
                    <div className="bg-center bg-no-repeat bg-cover p-[10px]" style={{ backgroundImage: `url(${b1})` }}>
                        <div className='bg-[#FD164040] h-full w-full border-2 border-[#FD1640]  flex flex-col justify-end p-[20px] pt-[150px]'>
                            <div className='font-zen-dots text-[32px] font-normal leading-normal'>Bagvaan</div>
                            <div className='font-zen-dots text-[20px] font-normal leading-normal'>Art by <span className='text-[#FD1640]'>xyz</span></div>
                        </div>
                    </div>
                    <div className="row-span-2 col-span-2 bg-center bg-no-repeat bg-cover p-[10px]" style={{ backgroundImage: `url(${b2})` }}>
                        <div className='bg-[#FD164040] h-full w-full border-2 border-[#FD1640]  flex flex-col justify-end p-[20px] pt-[150px]'>
                            <div className='font-zen-dots text-[32px] font-normal leading-normal'>Bagvaan</div>
                            <div className='font-zen-dots text-[20px] font-normal leading-normal'>Art by <span className='text-[#FD1640]'>xyz</span></div>
                        </div>
                    </div>
                    <div className="bg-center bg-no-repeat bg-cover p-[10px]" style={{ backgroundImage: `url(${b3})` }}>
                        <div className='bg-[#FD164040] h-full w-full border-2 border-[#FD1640]  flex flex-col justify-end p-[20px] pt-[150px]'>
                            <div className='font-zen-dots text-[32px] font-normal leading-normal'>Bagvaan</div>
                            <div className='font-zen-dots text-[20px] font-normal leading-normal'>Art by <span className='text-[#FD1640]'>xyz</span></div>
                        </div>
                    </div>
                    <div className="row-span-2 bg-center bg-no-repeat bg-cover p-[10px]" style={{ backgroundImage: `url(${b4})` }}>
                        <div className='bg-[#FD164040] h-full w-full border-2 border-[#FD1640]  flex flex-col justify-end p-[20px] pt-[150px]'>
                            <div className='font-zen-dots text-[32px] font-normal leading-normal'>Bagvaan</div>
                            <div className='font-zen-dots text-[20px] font-normal leading-normal'>Art by <span className='text-[#FD1640]'>xyz</span></div>
                        </div>
                    </div>
                    <div className="bg-center bg-no-repeat bg-cover p-[10px]" style={{ backgroundImage: `url(${b5})` }}>
                        <div className='bg-[#FD164040] h-full w-full border-2 border-[#FD1640]  flex flex-col justify-end p-[20px] pt-[150px]'>
                            <div className='font-zen-dots text-[32px] font-normal leading-normal'>Bagvaan</div>
                            <div className='font-zen-dots text-[20px] font-normal leading-normal'>Art by <span className='text-[#FD1640]'>xyz</span></div>
                        </div>
                    </div>
                    <div className="bg-center bg-no-repeat bg-cover p-[10px]" style={{ backgroundImage: `url(${b6})` }}>
                        <div className='bg-[#FD164040] h-full w-full border-2 border-[#FD1640]  flex flex-col justify-end p-[20px] pt-[150px]'>
                            <div className='font-zen-dots text-[32px] font-normal leading-normal'>Bagvaan</div>
                            <div className='font-zen-dots text-[20px] font-normal leading-normal'>Art by <span className='text-[#FD1640]'>xyz</span></div>
                        </div>
                    </div>
                    <div className="col-span-2 bg-center bg-no-repeat bg-cover p-[10px]" style={{ backgroundImage: `url(${b7})` }}>
                        <div className='bg-[#FD164040] h-full w-full border-2 border-[#FD1640]  flex flex-col justify-end p-[20px] pt-[150px]'>
                            <div className='font-zen-dots text-[32px] font-normal leading-normal'>Bagvaan</div>
                            <div className='font-zen-dots text-[20px] font-normal leading-normal'>Art by <span className='text-[#FD1640]'>xyz</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Popular